#!/usr/bin/env bash
#short and sweet bash script that configures container
sudo sed -i 's/user .*/user nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/listen .*/listen 8080;/g' /etc/nginx/sites-enabled/default
sudo chmod -R 755 /etc/nginx/
sudo pkill nginx
sudo -u nginx nginx
