#!/usr/bin/env bash
#short and sweet bash script that configures container
sudo chmod -R 755 /etc/nginx/
sudo pkill apache2
sudo sed -i 's/8080/8081/g' /etc/apache2/ports.conf
sudo service apache2 restart
sudo service nginx restart
