#!/usr/bin/env bash
# Configures Nginx to listen on port 80 and starts the service
apt-get update -y
apt-get install -y nginx
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx start

